# Generated by Django 2.1.5 on 2019-01-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replies', models.IntegerField(default=0)),
                ('last_reply', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(max_length=20000)),
                ('date_submitted', models.IntegerField(default=0)),
                ('reply_to', models.CharField(db_index=True, max_length=255, null=True)),
                ('user_id', models.CharField(max_length=100)),
                ('nsfw', models.BooleanField(default=False)),
                ('signature', models.CharField(max_length=255)),
                ('payload_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('block_time', models.IntegerField(default=0)),
                ('block_height', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'infnote_posts',
            },
        ),
    ]
